GET   http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Authorization: Token f2b82d869ed48cb25d7d9aba69263c0b30f890d2
Content-Type: application/json

# {"ingredients": [
# {
# "id": 2,
# "amount": 10
# }
# ],
# "tags": [
# 1,
# 2
# ],
# "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
# "name": "string",
# "text": 123,
# "cooking_time": 3
# }