# Generated by Django 3.2.4 on 2022-12-12 15:02

from django.db import migrations

INITIAL_TAGS = [
    {'color': 'orange', 'name': 'Breakfast', 'slug': 'breakfast'},
    {'color': 'green', 'name': 'Lunch', 'slug': 'lanch'},
    {'color': 'purple', 'name': 'Dinner', 'slug': 'dinner'},
]

def add_tags(apps, schema_editor):
    Tag = apps.get_model("api", "Tag")
    for tag in INITIAL_TAGS:
        new_tag = Tag(**tag)
        new_tag.save()

def remove_tags(apps, schema_editor):
    Tag = apps.get_model("api", "Tag")
    for tag in INITIAL_TAGS:
        Tag.objects.get(slug=tag['slug']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            remove_tags
        )
    ]
