# Generated by Django 3.2.16 on 2022-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(default=None, related_name='favorites', to='api.Favorite'),
        ),
    ]
