# Generated by Django 3.2.16 on 2022-12-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='favorites', to='api.Favorite'),
        ),
    ]
